/* SPDX-License-Identifier: MIT */
/* m68kops.h - GENERATED by tools/gen_m68k.py. Do not edit. */
#ifndef M68KOPS__HEADER
#define M68KOPS__HEADER

/* the handler pointers are few and hot, so they are data (RAM); the two 64K-entry
 * tables are constants (flash) */
#ifndef M68K_HANDLER_ATTR
#define M68K_HANDLER_ATTR
#endif
#define M68KI_NUM_HANDLERS 1701
extern void (* M68K_HANDLER_ATTR m68ki_handlers[1701])(void);
extern const unsigned short m68ki_op_index[0x10000];
extern unsigned char M68K_HANDLER_ATTR m68ki_handler_cycles[1701];

#endif /* M68KOPS__HEADER */
