/* SPDX-License-Identifier: 0BSD  Copyright (C) 2026 Jesse Castro
 * Written for PELLETINO; hardware behaviour referenced against MAME (BSD-3-Clause).
 * See LICENSING.md, "Emulator cores and MAME". */
/*
 * galaxian.h - Namco/Midway Galaxian (1979) board emulation
 *
 * The board Frogger was later built from: a Z80 at 3.072 MHz, 10 KB of program, 1 KB of work
 * RAM, a 32x32 tilemap of 8x8 characters with a vertical scroll per column, eight 16x16
 * sprites, eight one-pixel-wide "shells" (the shots, four pixels long), and a starfield
 * generated by a shift register that scrolls a line a frame. The monitor is rotated 90
 * degrees, so the picture is taller than it is wide.
 *
 * The sound board is discrete: a counter chain for the background hum (three octaves of
 * square wave, pitched by a register and gated by three enables), a 555 swept by a four-bit
 * LFO for the dive whistle, a noise generator for explosions and a swept tone for the shot.
 * galaxian_sound.c synthesises those; MAME runs the circuits themselves.
 *
 * Timing, memory map and video follow MAME's galaxian.cpp and galaxian_v.cpp.
 */
#ifndef GALAXIAN_H
#define GALAXIAN_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif

#define GX_MAIN_CLOCK   3072000                 /* 18.432 MHz / 6 */
/* 18.432 MHz pixel clock over 384 x 264 gives 60.606 Hz */
#define GX_CYCLES_PER_FRAME  50688              /* 3072000 / 60.606 */

/* the monitor is rotated, so the picture is taller than it is wide */
#define GX_FB_W 224
#define GX_FB_H 256
#define GX_PALETTE_SIZE 98                      /* 32 from the PROM, two shell colours, 64 star colours */
#define GX_PEN_WHITE    32
#define GX_PEN_YELLOW   33
#define GX_PEN_STARS    34

typedef struct {
    const uint8_t *rom;        /* 10 KB program, 0x0000-0x27FF */
    const uint8_t *gfx;        /* 4 KB: character plane 1 then plane 0 */
    const uint8_t *prom;       /* 32-byte colour PROM */
} gx_roms_t;

typedef struct {
    uint8_t left, right, fire;
    uint8_t start1, start2, coin1;
} gx_input_t;

void gx_init(const gx_roms_t *roms);
void gx_reset(void);
/* IN1 bits 6-7 are the coinage (0 = 1 coin 1 play); IN2 bits 0-1 the bonus life (0 = 7000),
 * bit 2 the lives (set = 3, clear = 2) */
void gx_set_dips(uint8_t in1, uint8_t in2);
gx_input_t *gx_input(void);

void gx_run_frame(void);
void gx_video_init(void);                       /* expands the character ROM; call once */
void gx_render(uint8_t *fb);                    /* GX_FB_W * GX_FB_H palette indices */
void gx_palette(uint16_t out[GX_PALETTE_SIZE]); /* RGB565 */
void gx_render_audio(int16_t *buf, int samples, int rate);

/* diagnostics */
uint16_t gx_pc(void);
uint32_t gx_frame_count(void);
const uint8_t *gx_ram(void);

/* the sound board (galaxian_sound.c). reg 0-7 are the latches at 0x6800-0x6807, 0x10-0x13
 * the LFO frequency bits at 0x6004-0x6007, 0x20 the pitch register at 0x7800 */
void gx_sound_reset(void);
void gx_sound_write(int reg, uint8_t v);

#ifdef __cplusplus
}
#endif
#endif
