#!/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Regenerate core/m68k/m68kops.c and m68kops.h from Musashi's own generator.

usage: tools/gen_m68k.py        (needs a host C compiler; writes into core/m68k/)

Musashi builds its opcode tables at start-up, in RAM: a 256 KB table of handler
pointers and 64 KB of cycle counts for each of five CPU types. This board has
512 KB of RAM in all, so the tables are worked out here instead and written as
constants that the linker puts in flash:

  m68ki_op_index[65536]    uint16  which handler an opcode uses      128 KB, flash
  m68ki_handlers[N]        pointer the handlers themselves           ~7 KB, RAM
  m68ki_handler_cycles[N]  uint8   what each costs on a 68000        ~2 KB, RAM

Musashi keeps the cost by opcode, 64 KB of it. Here it is kept by handler: a handler that
is listed with two different costs gets two entries, so the index that finds the handler
finds the cost too.

Only the 68000 is described. An opcode that Musashi gives no 68000 cycle count
is illegal on a 68000 and is left pointing at the illegal-instruction handler.

The steps: compile gen/m68kmake.c, run it over gen/m68k_in.c (both are Musashi's
files, unmodified), drop the table builder from the m68kops.c it writes, and put
the constant tables in its place. The order the entries are applied in is the
order Musashi applies them in, so a later, more specific entry still wins.
"""
import re, subprocess, sys, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
M68K = HERE.parent / 'core' / 'm68k'

def main():
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        subprocess.run(['cc', '-w', '-o', str(tmp / 'm68kmake'), str(M68K / 'gen' / 'm68kmake.c')], check=True)
        subprocess.run([str(tmp / 'm68kmake'), str(tmp), str(M68K / 'gen' / 'm68k_in.c')], check=True,
                       stdout=subprocess.DEVNULL)
        src = (tmp / 'm68kops.c').read_text()

    cut = src.index('/* ========================= OPCODE TABLE BUILDER')
    cut = src.rindex('/* =====', 0, cut)
    handlers_src, builder = src[:cut], src[cut:]

    # no FPU and no MMU on a 68000: their handlers go, and so do the externs they call
    handlers_src = re.sub(r'extern void m68(040_fpu_op[01]|881_mmu_ops)\(void\);\n', '', handlers_src)
    handlers_src = re.sub(r'\t\tm68(040_fpu_op[01]|881_mmu_ops)\(\);\n', '', handlers_src)
    handlers_src = handlers_src.replace('#include <stdio.h>\n', '', 1)
    handlers_src = handlers_src.replace('CYC_INSTRUCTION[REG_IR]', 'CYC_INSTRUCTION_IR')   # the cost is by handler here
    handlers_src = re.sub(r'\t\tfprintf\(stderr,[^\n]*\n', '', handlers_src)     # nothing prints on the device

    entries = re.findall(r'\{(m68k_op_\w+)\s*,\s*0x([0-9a-f]{4}),\s*0x([0-9a-f]{4}),\s*\{\s*(\d+),', builder)
    if len(entries) < 1900:
        sys.exit(f'only {len(entries)} table entries found; has Musashi changed its format?')

    # one entry for each (handler, cost) pair, so the cost can be looked up by the same
    # index as the handler and the 64 KB table of costs by opcode is not needed
    pairs = [('m68k_op_illegal', 0)]
    index = [0] * 0x10000
    for name, mask, match, cyc in entries:
        mask, match, cyc = int(mask, 16), int(match, 16), int(cyc)
        if cyc == 0:
            continue                       # not a 68000 instruction
        if (name, cyc) not in pairs:
            pairs.append((name, cyc))
        n = pairs.index((name, cyc))
        for op in range(0x10000):
            if (op & mask) == match:
                index[op] = n
    names = [n for n, c in pairs]
    cycles = [c for n, c in pairs]
    # the illegal-instruction exception is charged by the exception itself

    def rows(vals, per, fmt):
        return '\n'.join('\t' + ','.join(fmt % v for v in vals[i:i + per]) + ',' for i in range(0, len(vals), per))

    out = [
        '/* SPDX-License-Identifier: MIT */',
        '/*',
        ' * m68kops.c - GENERATED by tools/gen_m68k.py from Musashi 4.10 (gen/m68k_in.c). Do not edit.',
        ' *',
        ' * The instruction handlers are Musashi\'s, Copyright 1998-2001 Karl Stenerud, MIT licence',
        ' * (see readme.txt). The tables at the end are what m68ki_build_opcode_table() would have',
        ' * built at start-up for a 68000, worked out ahead of time so they can live in flash.',
        ' */',
        handlers_src.rstrip(),
        '',
        '',
        '/* ======================================================================== */',
        '/* ===================== OPCODE TABLES (68000, constant) ================== */',
        '/* ======================================================================== */',
        '',
        '#include "m68kops.h"',
        '',
        f'void (* M68K_HANDLER_ATTR m68ki_handlers[{len(names)}])(void) =',
        '{',
        '\n'.join(f'\t{n},' for n in names),
        '};',
        '',
        'const unsigned short m68ki_op_index[0x10000] =',
        '{',
        rows(index, 16, '%4d'),
        '};',
        '',
        f'unsigned char M68K_HANDLER_ATTR m68ki_handler_cycles[{len(names)}] =',
        '{',
        rows(cycles, 32, '%2d'),
        '};',
        '',
    ]
    (M68K / 'm68kops.c').write_text('\n'.join(out))
    (M68K / 'm68kops.h').write_text('\n'.join([
        '/* SPDX-License-Identifier: MIT */',
        '/* m68kops.h - GENERATED by tools/gen_m68k.py. Do not edit. */',
        '#ifndef M68KOPS__HEADER',
        '#define M68KOPS__HEADER',
        '',
        '/* the handler pointers are few and hot, so they are data (RAM); the two 64K-entry',
        ' * tables are constants (flash) */',
        '#ifndef M68K_HANDLER_ATTR',
        '#define M68K_HANDLER_ATTR',
        '#endif',
        f'#define M68KI_NUM_HANDLERS {len(names)}',
        f'extern void (* M68K_HANDLER_ATTR m68ki_handlers[{len(names)}])(void);',
        'extern const unsigned short m68ki_op_index[0x10000];',
        f'extern unsigned char M68K_HANDLER_ATTR m68ki_handler_cycles[{len(names)}];',
        '',
        '#endif /* M68KOPS__HEADER */',
        '',
    ]))
    legal = sum(1 for i in index if i)
    print(f'{len(entries)} table entries, {len(names)} handlers in use, {legal} legal 68000 opcodes')

if __name__ == '__main__':
    main()
