#!/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Regenerate core/m68k/m68kops.c and m68kops.h from Musashi's own generator.

usage: tools/gen_m68k.py        (needs a host C compiler; writes into core/m68k/)

Musashi builds its opcode tables at start-up, in RAM: a 256 KB table of handler
pointers and 64 KB of cycle counts for each of five CPU types. This board has
512 KB of RAM in all, so the tables are worked out here instead and written as
constants that the linker puts in flash:

  m68ki_op_group[8192]     uint16  by opcode >> 3: a handler, or a row   16 KB
  m68ki_op_rows[N * 8]     uint16  the rows, for groups that need one     5 KB
  m68ki_handlers[N]        pointer the handlers themselves                7 KB
  m68ki_handler_cycles[N]  uint8   what each costs on a 68000             2 KB

which is 30 KB where Musashi's were 576 KB, and small enough to be kept in RAM, where
looking an opcode up does not go through the flash cache.

Musashi keeps the cost by opcode, 64 KB of it. Here it is kept by handler: a handler that
is listed with two different costs gets two entries, so the index that finds the handler
finds the cost too.

Only the 68000 is described. An opcode that Musashi gives no 68000 cycle count
is illegal on a 68000 and is left pointing at the illegal-instruction handler.

The steps: compile gen/m68kmake.c, run it over gen/m68k_in.c (both are Musashi's
files, unmodified), drop the table builder from the m68kops.c it writes, and put
the constant tables in its place. The order the entries are applied in is the
order Musashi applies them in, so a later, more specific entry still wins.
"""
import re, subprocess, sys, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
M68K = HERE.parent / 'core' / 'm68k'

def main():
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        subprocess.run(['cc', '-w', '-o', str(tmp / 'm68kmake'), str(M68K / 'gen' / 'm68kmake.c')], check=True)
        subprocess.run([str(tmp / 'm68kmake'), str(tmp), str(M68K / 'gen' / 'm68k_in.c')], check=True,
                       stdout=subprocess.DEVNULL)
        src = (tmp / 'm68kops.c').read_text()

    cut = src.index('/* ========================= OPCODE TABLE BUILDER')
    cut = src.rindex('/* =====', 0, cut)
    handlers_src, builder = src[:cut], src[cut:]

    # no FPU and no MMU on a 68000: their handlers go, and so do the externs they call
    handlers_src = re.sub(r'extern void m68(040_fpu_op[01]|881_mmu_ops)\(void\);\n', '', handlers_src)
    handlers_src = re.sub(r'\t\tm68(040_fpu_op[01]|881_mmu_ops)\(\);\n', '', handlers_src)
    handlers_src = handlers_src.replace('#include <stdio.h>\n', '', 1)
    handlers_src = handlers_src.replace('CYC_INSTRUCTION[REG_IR]', 'CYC_INSTRUCTION_IR')   # the cost is by handler here
    handlers_src = re.sub(r'\t\tfprintf\(stderr,[^\n]*\n', '', handlers_src)     # nothing prints on the device

    entries = re.findall(r'\{(m68k_op_\w+)\s*,\s*0x([0-9a-f]{4}),\s*0x([0-9a-f]{4}),\s*\{\s*(\d+),', builder)
    if len(entries) < 1900:
        sys.exit(f'only {len(entries)} table entries found; has Musashi changed its format?')

    # one entry for each (handler, cost) pair, so the cost can be looked up by the same
    # index as the handler and the 64 KB table of costs by opcode is not needed
    pairs = [('m68k_op_illegal', 0)]
    index = [0] * 0x10000
    for name, mask, match, cyc in entries:
        mask, match, cyc = int(mask, 16), int(match, 16), int(cyc)
        if cyc == 0:
            continue                       # not a 68000 instruction
        if (name, cyc) not in pairs:
            pairs.append((name, cyc))
        n = pairs.index((name, cyc))
        for op in range(0x10000):
            if (op & mask) == match:
                index[op] = n
    names = [n for n, c in pairs]
    cycles = [c for n, c in pairs]
    # the illegal-instruction exception is charged by the exception itself

    def rows(vals, per, fmt):
        return '\n'.join('\t' + ','.join(fmt % v for v in vals[i:i + per]) + ',' for i in range(0, len(vals), per))

    # Two levels. Opcodes that differ only in their low three bits (a register number, as a
    # rule) mostly share a handler, so the table is by opcode >> 3, and a group whose eight
    # opcodes do not all share one points at a row of eight instead.
    groups, rowlist, rowof = [], [], {}
    for g in range(0x2000):
        row = tuple(index[g * 8:g * 8 + 8])
        if len(set(row)) == 1:
            groups.append(row[0])
        else:
            if row not in rowof:
                rowof[row] = len(rowlist)
                rowlist.append(row)
            groups.append(0x8000 | rowof[row])
    flat = [v for r in rowlist for v in r]

    out = [
        '/* SPDX-License-Identifier: MIT */',
        '/*',
        ' * m68kops.c - GENERATED by tools/gen_m68k.py from Musashi 4.10 (gen/m68k_in.c). Do not edit.',
        ' *',
        ' * The instruction handlers are Musashi\'s, Copyright 1998-2001 Karl Stenerud, MIT licence',
        ' * (see readme.txt). The tables at the end are what m68ki_build_opcode_table() would have',
        ' * built at start-up for a 68000, worked out ahead of time and packed.',
        ' */',
        handlers_src.rstrip(),
        '',
        '',
        '/* ======================================================================== */',
        '/* ===================== OPCODE TABLES (68000, constant) ================== */',
        '/* ======================================================================== */',
        '',
        '#include "m68kops.h"',
        '',
        f'void (* M68K_HANDLER_ATTR m68ki_handlers[{len(names)}])(void) =',
        '{',
        '\n'.join(f'\t{n},' for n in names),
        '};',
        '',
        f'unsigned char M68K_HANDLER_ATTR m68ki_handler_cycles[{len(names)}] =',
        '{',
        rows(cycles, 32, '%2d'),
        '};',
        '',
        '/* by opcode >> 3: a handler, or with the top bit set, a row of m68ki_op_rows */',
        'M68K_GROUP_ATTR unsigned short m68ki_op_group[0x2000] =',
        '{',
        rows(groups, 16, '0x%04x'),
        '};',
        '',
        f'M68K_ROW_ATTR unsigned short m68ki_op_rows[{len(flat)}] =',
        '{',
        rows(flat, 8, '%4d'),
        '};',
        '',
    ]
    (M68K / 'm68kops.c').write_text('\n'.join(out))
    (M68K / 'm68kops.h').write_text('\n'.join([
        '/* SPDX-License-Identifier: MIT */',
        '/* m68kops.h - GENERATED by tools/gen_m68k.py. Do not edit. */',
        '#ifndef M68KOPS__HEADER',
        '#define M68KOPS__HEADER',
        '',
        '#include "m68kconf.h"',
        '',
        '/* Where the tables live is the builder\'s choice (m68kconf.h): nothing here says const,',
        ' * so without an attribute they are data and are in RAM. */',
        '#ifndef M68K_HANDLER_ATTR',
        '#define M68K_HANDLER_ATTR',
        '#endif',
        '#ifndef M68K_GROUP_ATTR',
        '#define M68K_GROUP_ATTR',
        '#endif',
        '#ifndef M68K_ROW_ATTR',
        '#define M68K_ROW_ATTR',
        '#endif',
        f'#define M68KI_NUM_HANDLERS {len(names)}',
        f'extern void (* M68K_HANDLER_ATTR m68ki_handlers[{len(names)}])(void);',
        f'extern unsigned char M68K_HANDLER_ATTR m68ki_handler_cycles[{len(names)}];',
        'extern M68K_GROUP_ATTR unsigned short m68ki_op_group[0x2000];',
        f'extern M68K_ROW_ATTR unsigned short m68ki_op_rows[{len(flat)}];',
        '',
        '/* which handler an opcode uses */',
        'static inline unsigned int m68ki_handler_of(unsigned int op)',
        '{',
        '\tunsigned int g = m68ki_op_group[op >> 3];',
        '\treturn (g & 0x8000) ? m68ki_op_rows[((g & 0x7fff) << 3) | (op & 7)] : g;',
        '}',
        '',
        '#endif /* M68KOPS__HEADER */',
        '',
    ]))
    legal = sum(1 for i in index if i)
    print(f'{len(entries)} table entries, {len(names)} handlers in use, {legal} legal 68000 opcodes; '
          f'tables: {len(groups) * 2} + {len(flat) * 2} + {len(names) * 5} bytes')

if __name__ == '__main__':
    main()
