#!/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Choose which of the 68000's instruction handlers run from RAM.

usage: tools/hot.py <profile> [percent]      (default 99)

The profile is what the host harness writes when it is built with -DCPS1_PROFILE and run
with PROFILE_OUT=<file>: how many times each opcode was executed.

    make -C host -B OPT="-O2 -DCPS1_PROFILE"
    PROFILE_OUT=/tmp/profile.txt host/harness roms.bin /tmp 400 --every 100000 --quiet
    tools/hot.py /tmp/profile.txt

Musashi has a function for each form of each instruction, 1700 of them for a 68000, and a
program uses a few of them nearly all the time. The handlers are ranked by how often they
ran, and the most used, up to the given share of all instructions executed, are listed in
components/emu/linker.lf to be placed in RAM. linker_cold.lf is the same file without
them, for HOT_HANDLERS=0.

What is written is a list of kinds of 68000 instruction ("move.w from a data register to
a data register"). Nothing of the program that was profiled is in it.
"""
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BASE = '''# What runs from RAM rather than through the flash cache. RAM is the scarce thing on this
# board, so this is the inner loops only: the machine, the video, the 68000's dispatch loop
# and the sound chips. The Z80 stays in flash: in RAM it is 65 KB, and with that gone the
# machine's graphics RAM does not fit.
#
# GENERATED by tools/hot.py. Do not edit.
[mapping:emu]
archive: libemu.a
entries:
    cps1 (noflash)
    cps1_video (noflash)
    cps1_sound (noflash)
    cps1_idle (noflash)
    ym2151 (noflash)
    okim6295 (noflash)
    m68kcpu (noflash)
    m68kown (noflash)
'''

def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    want = float(sys.argv[2]) if len(sys.argv) > 2 else 99.0
    ops = {}
    for line in open(sys.argv[1]):
        kind, a, n = line.split()
        if kind == 'op':
            ops[int(a, 16)] = int(n)
    src = (ROOT / 'core' / 'm68k' / 'm68kops.c').read_text()
    def table(name):
        body = re.search(name + r'\[[^\]]*\]\)?(?:\(void\))? =\n\{\n(.*?)\n\};', src, re.S).group(1)
        return [x for x in re.split(r'[\s,]+', body) if x]
    names = table(r'm68ki_handlers')
    group = [int(x, 16) for x in table(r'm68ki_op_group')]
    rows = [int(x) for x in table(r'm68ki_op_rows')]
    def handler(op):
        g = group[op >> 3]
        return rows[((g & 0x7fff) << 3) | (op & 7)] if g & 0x8000 else g
    hits = {}
    for op, n in ops.items():
        h = names[handler(op)]
        hits[h] = hits.get(h, 0) + n
    total = sum(hits.values())
    ranked = sorted(hits.items(), key=lambda x: -x[1])
    hot, acc = [], 0
    for name, n in ranked:
        if 100.0 * acc / total >= want:
            break
        hot.append(name)
        acc += n
    lf = ROOT / 'components' / 'emu'
    (lf / 'linker_cold.lf').write_text(BASE.replace('and the sound chips.', 'and the sound chips. None of the 68000\'s 1700 instruction\n# handlers: this is the file for HOT_HANDLERS=0.'))
    (lf / 'linker.lf').write_text(
        BASE.replace('and the sound chips.', f'and the sound chips, and the {len(hot)} of the 68000\'s 1700\n# instruction handlers that were {100.0 * acc / total:.1f}% of what a profile of attract mode executed.')
        + f'    # the {len(hot)} most used instruction handlers, most used first\n'
        + ''.join(f'    m68kops:{n} (noflash)\n' for n in hot))
    print(f'{len(ranked)} handlers ran; the {len(hot)} most used are {100.0 * acc / total:.2f}% of {total} instructions')

if __name__ == '__main__':
    main()
