#!/usr/bin/env bash
#
# Flash a complete medal: bootloader, partition table, ota_data, launcher,
# marquee artwork, and every game that has been built - each to its own slot.
#
# Offsets come from build/manifest.json and partitions.csv, both generated by
# tools/configure.py, so they cannot drift from what the firmware expects.
#
#   tools/flash_all.sh [port]
#   tools/flash_all.sh --dry-run
#
# Run from the host. Docker Desktop on macOS cannot reach USB devices.
set -euo pipefail
cd "$(dirname "$0")/.."

DRY=0; PORT=""
for a in "$@"; do
    case "$a" in
        --dry-run) DRY=1 ;;
        *) PORT="$a" ;;
    esac
done

BUILD=build_docker
MANIFEST=build/manifest.json
# the game repos live in games/, each its own git repo; override with PROJECTS_DIR
PROJECTS="${PROJECTS_DIR:-$PWD/games}"

[ -f "$MANIFEST" ]        || { echo "no $MANIFEST - run ./pelletino build" >&2; exit 1; }
[ -f "$BUILD/pelletino.bin" ] || { echo "no launcher build - run ./pelletino build" >&2; exit 1; }
[ -f lcd/marquees.bin ]   || { echo "no lcd/marquees.bin - run ./pelletino build" >&2; exit 1; }

mqart_off=$(awk -F',' '/^mqart/ {gsub(/ /,"",$4); print $4}' partitions.csv)

ARGS=(0x0     "$BUILD/bootloader/bootloader.bin"
      0x8000  "$BUILD/partition_table/partition-table.bin"
      0xf000  "$BUILD/ota_data_initial.bin"
      0x20000 "$BUILD/pelletino.bin"
      "$mqart_off" lcd/marquees.bin)

echo
printf '  %-22s %-10s %s\n' COMPONENT OFFSET FILE
printf '  %-22s %-10s %s\n' launcher 0x20000 "$BUILD/pelletino.bin"
printf '  %-22s %-10s %s\n' artwork "$mqart_off" lcd/marquees.bin

missing=0
while IFS=$'\t' read -r rom title project binary offset data_file data_offset owner; do
    [ -n "$rom" ] || continue
    # a shared-slot rider (Pac-Man on Ms. Pac-Man) has no image of its own; the
    # owner already flashes that slot, so skip it here to avoid a duplicate write
    if [ -n "$owner" ] && [ "$owner" != "-" ] && [ "$owner" != "null" ]; then
        printf '  %-22s %-10s %s(rides %s)%s\n' "$title" "$offset" $'\033[2m' "$owner" $'\033[0m'
        continue
    fi
    bin=""
    if [ -n "$project" ] && [ "$project" != "null" ]; then
        # '-' means games.toml named no binary; an empty field would be swallowed by read
        if [ -n "$binary" ] && [ "$binary" != "-" ]; then
            # games.toml named the binary: one project can build more than one game
            cand="$PROJECTS/$project/$binary"
        else
            # a game repo builds to <PROJECT>/build_docker/<lowercase project>.bin
            cand="$PROJECTS/$project/build_docker/$(echo "$project" | tr 'A-Z' 'a-z').bin"
        fi
        [ -f "$cand" ] && bin="$cand"
    fi
    if [ -n "$bin" ]; then
        printf '  %-22s %-10s %s\n' "$title" "$offset" "${bin#$PROJECTS/}"
        ARGS+=("$offset" "$bin")
        # the game's own data partition, if games.toml gave it one
        if [ "$data_file" != "-" ] && [ -f "$PROJECTS/$project/$data_file" ]; then
            printf '  %-22s %-10s %s\n' "  $title data" "$data_offset" "$project/$data_file"
            ARGS+=("$data_offset" "$PROJECTS/$project/$data_file")
        elif [ "$data_file" != "-" ]; then
            printf '  %-22s %-10s %s(%s missing - partition left empty)%s\n' "  $title data" "$data_offset" $'\033[2m' "$data_file" $'\033[0m'
        fi
    else
        printf '  %-22s %-10s %s(not built - slot left empty)%s\n' "$title" "$offset" $'\033[2m' $'\033[0m'
        missing=$((missing+1))
    fi
done < <(python3 -c "
import json
for g in json.load(open('$MANIFEST'))['games']:
    if g.get('builtin'): continue          # lives in the launcher: nothing to flash
    print('\t'.join([g['rom'], g['title'], str(g.get('project') or ''), str(g.get('binary') or '-'), hex(g['offset']),
                     str(g.get('data_file') or '-'), hex(g.get('data_offset') or 0), str(g.get('owner') or '-')]))
")

ESPTOOL=$(command -v esptool.py || echo "python3 -m esptool")
CMD=($ESPTOOL --chip esp32c6 ${PORT:+-p "$PORT"} -b 460800
     --before default_reset --after hard_reset
     write_flash --flash_mode dio --flash_size 16MB --flash_freq 80m "${ARGS[@]}")

echo
[ "$missing" -gt 0 ] && echo "  $missing slot(s) empty - those games show as NOT INSTALLED in the menu"

if [ "$DRY" = 1 ]; then
    echo; echo "  dry run, would execute:"; echo; printf '   %q' "${CMD[@]}"; echo; echo
    exit 0
fi
echo; echo "  flashing..."; echo
"${CMD[@]}"
